swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
x-a127-config: {}
x-a127-services: {}
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    x-a127-apply: {}
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /mashup:
    # binds a127 app logic to a route
    x-swagger-router-controller: mashup
    x-a127-apply: {}
    get:
      description: Returns a session/speaker complete payload to the caller
      # used as the method name of the controller
      operationId: mashup
      parameters:
        - name: sessionTitleFragment
          in: query
          description:  Any string that appears in the title of a session
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/MashupResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  MashupResponse:
    required:
      - name
      - title
      - uuid
      - speaker
      - bio
    properties:
      name:
        type: string
      title:
        type: string
      uuid:
        type: string
      date:
        type: string
      time:
        type: string
      room:
        type: string
      description:
        type: string
      speaker:
        type: string
      bio:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
